### ISSUE TITLE
Milestone 0.7.1

### ISSUE THREAD

**Issue by lachlanmcdonald** [lachlanmcdonald/postcss-filter-rules#23]
- [ ] Keep a `@keyframes` rule when it is referenced by `animation-name` or the `animation` shorthand.
- [ ] Keep a `@font-face` rule when it is referenced by `font-family` or the `font` shorthand.
- [ ] Allow custom callbacks for `charset`, `import`, and `keyframes` blocks.
- [ ] Switch to PostCSS 8's plugins methods for improved performance.
